# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Jacob Bergam
tagline:             jacobbergam.com
description:         "System and Integration Engineer, <br> UC Santa Barbara"
url:                 http://JacobBergam.com
baseurl:             ''
encoding:            utf-8
paginate:            5

# Plugins, Tags, Categories and Analytics  
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate  
  - jekyll-seo-tag

# About/contact
author:
  name:              Jacob Bergam
  url:               https://jacobbergam.com
  email:             jabergam@gmail.com


google_analytics:   UA-162535959-1

# Amazon Associates: set your tag to turn book links into affiliate links (e.g. yoursite-20).
# Leave blank to keep links pointing to Goodreads only.
amazon_associate_tag: "blogbooks21-20"


